//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBVI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LastInspection
    {
        public int LasInspectionId { get; set; }
        public string OCompanyName { get; set; }
        public int? ItemId { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int? WorkPlaceId { get; set; }
        public int UnCheckedQuantity { get; set; }
        public int CheckedQuantity { get; set; }
        public int PassState { get; set; }
        public int PassQuantity { get; set; }
        public int failQuantity { get; set; }
        public int FinalQuantity { get; set; }
        public string WorkerName { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual WorkPlace WorkPlace { get; set; }
    }
}
