//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBVI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBVIEntities : DbContext
    {
        public PCBVIEntities()
            : base("name=PCBVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode> Barcode { get; set; }
        public virtual DbSet<DefectiveProduct> DefectiveProduct { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<ErrorCode> ErrorCode { get; set; }
        public virtual DbSet<ErrorKind> ErrorKind { get; set; }
        public virtual DbSet<ErrorType> ErrorType { get; set; }
        public virtual DbSet<Facilities> Facilities { get; set; }
        public virtual DbSet<FacilitiesHistory> FacilitiesHistory { get; set; }
        public virtual DbSet<FacilitiesPower> FacilitiesPower { get; set; }
        public virtual DbSet<FHistoryDivision> FHistoryDivision { get; set; }
        public virtual DbSet<FirstInspection> FirstInspection { get; set; }
        public virtual DbSet<InspectionStandard> InspectionStandard { get; set; }
        public virtual DbSet<InspectionStandardType> InspectionStandardType { get; set; }
        public virtual DbSet<LastInspection> LastInspection { get; set; }
        public virtual DbSet<Lot> Lot { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistory { get; set; }
        public virtual DbSet<MaterialsInRe> MaterialsInRe { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<ProcessDefect> ProcessDefect { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductionHistory> ProductionHistory { get; set; }
        public virtual DbSet<ProductSubJect> ProductSubJect { get; set; }
        public virtual DbSet<RotationGroup> RotationGroup { get; set; }
        public virtual DbSet<TotalMonitoring> TotalMonitoring { get; set; }
        public virtual DbSet<WokGroup> WokGroup { get; set; }
        public virtual DbSet<Worker> Worker { get; set; }
        public virtual DbSet<WorkLog> WorkLog { get; set; }
        public virtual DbSet<WorkPlace> WorkPlace { get; set; }
    }
}
