//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBVI.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PCBVIEntities : DbContext
    {
        public PCBVIEntities()
            : base("name=PCBVIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Barcode> Barcodes { get; set; }
        public virtual DbSet<DefectiveProduct> DefectiveProducts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<ErrorCode> ErrorCodes { get; set; }
        public virtual DbSet<ErrorKind> ErrorKinds { get; set; }
        public virtual DbSet<ErrorType> ErrorTypes { get; set; }
        public virtual DbSet<Facility> Facilities { get; set; }
        public virtual DbSet<FacilitiesHistory> FacilitiesHistories { get; set; }
        public virtual DbSet<FacilitiesPower> FacilitiesPowers { get; set; }
        public virtual DbSet<FHistoryDivision> FHistoryDivisions { get; set; }
        public virtual DbSet<FirstInspection> FirstInspections { get; set; }
        public virtual DbSet<InspectionStandard> InspectionStandards { get; set; }
        public virtual DbSet<InspectionStandardType> InspectionStandardTypes { get; set; }
        public virtual DbSet<LastInspection> LastInspections { get; set; }
        public virtual DbSet<Lot> Lots { get; set; }
        public virtual DbSet<MaterialHistory> MaterialHistories { get; set; }
        public virtual DbSet<MaterialsInRe> MaterialsInRes { get; set; }
        public virtual DbSet<Process> Processes { get; set; }
        public virtual DbSet<ProcessDefect> ProcessDefects { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductionHistory> ProductionHistories { get; set; }
        public virtual DbSet<ProductSubJect> ProductSubJects { get; set; }
        public virtual DbSet<RotationGroup> RotationGroups { get; set; }
        public virtual DbSet<TotalMonitoring> TotalMonitorings { get; set; }
        public virtual DbSet<WokGroup> WokGroups { get; set; }
        public virtual DbSet<Worker> Workers { get; set; }
        public virtual DbSet<WorkLog> WorkLogs { get; set; }
        public virtual DbSet<WorkPlace> WorkPlaces { get; set; }
    }
}
