//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PCBVI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductionHistory()
        {
            this.FacilitiesPowers = new HashSet<FacilitiesPower>();
        }
    
        public int ProductionHistoryId { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public int ErrorCodeId { get; set; }
        public System.DateTime EndTime { get; set; }
        public int FacilitiesId { get; set; }
        public System.DateTime StartTime { get; set; }
        public int ProductId { get; set; }
        public string PassState { get; set; }
        public int Quantity { get; set; }
        public string WorkContent { get; set; }
    
        public virtual ErrorCode ErrorCode { get; set; }
        public virtual Facility Facility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FacilitiesPower> FacilitiesPowers { get; set; }
        public virtual Product Product { get; set; }
    }
}
